ALTER TABLE public.profiles
  ADD COLUMN prf_created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT now() NOT NULL;

COMMIT;

ALTER TABLE public.profiles
  ADD COLUMN prf_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL;

COMMIT;
